### ISSUE TITLE
Program crashes after setting options and then pressing start button

### ISSUE THREAD

**Issue by Bowlsys** [tinyMediaManager/tinyMediaManager#139]
Version: 2.9.2
Build: 2017-01-27 15:08
OS: Windows 8.1 6.3
JDK: 1.8.0_31 x86 Oracle Corporation

__What is the actual behaviour?__
Looked like a Java crash

__What is the expected behaviour?__

To start scanning the movies

__Steps to reproduce:__

Restarted the app and it does the same

__Additional__
java.lang.NullPointerException
	at org.tinymediamanager.ui.movies.MovieDetailsPanel$1.actionPerformed(MovieDetailsPanel.java:182)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at com.jtattoo.plaf.BaseButtonListener.mouseReleased(BaseButtonListener.java:60)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mlaggner** [comment]
this start button starts playback of the movie rather than scanning for new movies.
Unfortunately this movie has no associated video file - could it be that you removed the video file types from your settings prior to scanning?

**Comment by Bowlsys** [comment]
Very many thanks for your reply, yes I was using the arrow for the wrong purpose.

When I used the right method however , all my movies and tv series were found but all had x’s in all the columns.

When I used the scrape option  under the movies tab for each movie, all the info was loaded. Am I doing something wrong?

 

Regards

Tony Stephens

**Comment by myron0815** [comment]
Depends.
Did your movie has a NFO before? No? -> red X
Did your movie has a poster before? No? -> red X
...
Scraping fills all the goods for you from internet...
