### ISSUE TITLE
AniDB scraper fails and kicks up an error (multiple OSes)

### ISSUE THREAD

**Issue by defron** [tinyMediaManager/tinyMediaManager#216]
__What TMM version are you using?__
2.9.5

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Attempting to scrape TV show information using AniDB fails, attempting to search for TV shows using AniDB fails (works using other scrapers)

__What is the expected behaviour?__
To be able to successfully scrape TV show information using AniDB

__Steps to reproduce:__
- Add anime TV show
- Right-click and select "Search and Scrape selected TV Shows"
- Using AniDB scraper, attempt to search

__Additional__
Have you attached the Logfile from the day it happened?
Yes:

Linux: https://drive.google.com/open?id=0BxLzSXDt-FNAWFM1cTNNc05LVXc
Windows: https://drive.google.com/open?id=0BxLzSXDt-FNARUhMZklySFdFMzg

Your Operating system? (win/mac/linux? version?)
Linux: KDE Neon (based on Ubuntu LTS 16.04)
Windows: Windows Server 2008R2

Error:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at org.tinymediamanager.scraper.anidb.AniDBMetadataProvider.search(AniDBMetadataProvider.java:489)
	at org.tinymediamanager.core.tvshow.TvShowList.searchTvShow(TvShowList.java:508)
	at org.tinymediamanager.ui.tvshows.dialogs.TvShowChooserDialog$SearchTask.doInBackground(TvShowChooserDialog.java:521)
	at org.tinymediamanager.ui.tvshows.dialogs.TvShowChooserDialog$SearchTask.doInBackground(TvShowChooserDialog.java:507)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ProIcons** [comment]
In order to proceed with a fix, and since i don't have a Anime database on my TMM's instance. You have multiple Anime TVShows.  One of them has similar title with the one you are trying to add, and there are possible produced the same year. Is my assumption correct?

**Comment by defron** [comment]
yes that is correct. in anime, second seasons of shows often will be listed
differently and have similar titles (such as working!! And working'!! Or
dog days and dog days') and can be released in the same year in some cases.

Anyway I pulled down the fix and built it, replacing my api-scraper.jar
with it and it works now. Thanks!
