### ISSUE TITLE
Feature Request: Support Portable Java (Windows)

### ISSUE THREAD

**Issue by LeeThompson** [tinyMediaManager/tinyMediaManager#246]
I don't like having the installed version of the Java Runtime Environment on my systems, instead I use a portable installation that doesn't have it's hooks into anything.

Unfortunately, TMM does not appear to support running in this manner:

If I try to run "java -jar tmm.jar" I get:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ch/qos/logback/core/filter/Filter
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.filter.Filter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by myron0815** [comment]
try ```java -Dsilent=noupdate -jar getdown.jar .```
It is not possible to start TMM directly, since we need some special parameters and libraries, which is handled by our updater....

**Comment by ProIcons** [comment]
Complimentary comment to @myron0815 's we are planning to bundle a java distribution on our Version 3. This will allow portable installations of tmm, and will eliminate compatibility issues.

**Comment by mlaggner** [comment]
portable java is already supported, see https://github.com/tinyMediaManager/tinyMediaManager/wiki/FAQ#tinymediamanager-wont-start-with-java-portable

and shipping an own jre with tmm is on our ideas list, but I suppose this won't happen on v3 release - maybe later
