### ISSUE TITLE
sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData

### ISSUE THREAD

**Issue by lilithfr** [tinyMediaManager/tinyMediaManager#260]
__What TMM version are you using?__
tmm.version      : 2.9.7
java.version     : 1.8.0_161
default encoding : UTF-8 | UTF8 | UTF-8
set encoding to  : UTF-8 | UTF8 | UTF-8
System language  : en_US
GUI language     : en_US
Using MediaInfoLib - v0.7.98
OS: Ubuntu 17.10

__release, pre-release, nightly, or directly from GitHub/branch?__
Package: tmm_2.9.7_8513bee_linux.tar.gz from the website http://www.tinymediamanager.org

__What is the actual behavior?__
TMM is open and the computer goes into power saving mode (only the screen are powered off).
When I wake up the OS and enter the password, I see a popup with the following exception and every time I close the popup, it reappears; so I kill the process manually. Based on the log, the exception appears just after the wakeup.

```
2018-02-06 07:04:19,253 ERROR [main] org.tinymediamanager.Log4jBackstop:37 - Uncaught exception in thread: main
java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
        at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:148)
        at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:356)
        at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
        at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
        at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
        at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
        at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
        at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
        at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1589)
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
        at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:306)
        at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
        at javax.swing.JComponent.paint(JComponent.java:1042)
        at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
        at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
        at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
        at java.awt.Container.paint(Container.java:1976)
        at java.awt.Window.paint(Window.java:3906)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
        at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
        at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

__What is the expected behaviour?__
The exception should not appear or only 1 time.

__Steps to reproduce:__
- Start TMM.
- Wait for the power saving mode to activate 
- Wake up and enter password
- The popup appears.

__Additional__
Have you attached the Logfile from the day it happened? Yes
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/1699731/tmm.log)

Your Operating system? Ubuntu 17.10

**Comment by myron0815** [comment]
puh, seems to be a Java bug https://bugs.openjdk.java.net/browse/JDK-8147542
Might already be fixed in Java 9, and Java 8 update 172 (upcoming? next?)
Anyhow, we cannot do anything about it :(

**Comment by mlaggner** [comment]
the new java version is out - could you try that again?
