### ISSUE TITLE
tinyMediaManagerCMD throws exception

### ISSUE THREAD

**Issue by pschonmann** [tinyMediaManager/tinyMediaManager#3]
version=2.7-SNAPSHOT
build=nightly
date=2015-10-12 23\:23
```
d:\Appz\tinymediamanager>tinyMediaManagerCMD.exe -update
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.tinymediamanager.TinyMediaManager.<clinit>(TinyMediaManager.java:80)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by mlaggner** [comment]
the classpath was missing in the command line starters
eb6a7f773e53f894f411e856e6566c3860f5b9b9 addresses the windows command line starter

a fix for the linux starter will follow

**Comment by mlaggner** [comment]
should work with next nightly build for windows and linux users

**Comment by pschonmann** [comment]
Tried a shiny new exe. But ive got another one :)
```
d:\Appz\tinymediamanager>tinyMediaManagerCMD.exe -update
2015-10-14 00:54:09,049 DEBUG [main] org.tinymediamanager.TinyMediaManager:91 - TMM started with: [-update]
2015-10-14 00:54:09,069 INFO  [main] org.tinymediamanager.TinyMediaManager:141 - =====================================================
2015-10-14 00:54:09,070 INFO  [main] org.tinymediamanager.TinyMediaManager:142 - === tinyMediaManager (c) 2012-2015 Manuel Laggner ===
2015-10-14 00:54:09,070 INFO  [main] org.tinymediamanager.TinyMediaManager:143 - =====================================================
2015-10-14 00:54:09,072 INFO  [main] org.tinymediamanager.TinyMediaManager:144 - tmm.version      : 2.7-SNAPSHOT - NIGHTLY
2015-10-14 00:54:09,498 INFO  [main] org.tinymediamanager.TinyMediaManager:147 - tmm.supporter    : THANKS FOR DONATING - ALL FEATURES UNLOCKED :)
2015-10-14 00:54:09,499 INFO  [main] org.tinymediamanager.TinyMediaManager:150 - os.name          : Windows 10
2015-10-14 00:54:09,499 INFO  [main] org.tinymediamanager.TinyMediaManager:151 - os.version       : 10.0
2015-10-14 00:54:09,499 INFO  [main] org.tinymediamanager.TinyMediaManager:152 - os.arch          : amd64
2015-10-14 00:54:09,502 INFO  [main] org.tinymediamanager.TinyMediaManager:154 - java.version     : 1.8.0_60
2015-10-14 00:54:09,503 INFO  [main] org.tinymediamanager.TinyMediaManager:589 - default encoding : UTF-8 | UTF8 | UTF-8
2015-10-14 00:54:09,503 INFO  [main] org.tinymediamanager.TinyMediaManager:589 - set encoding to  : UTF-8 | UTF8 | UTF-8
2015-10-14 00:54:09,504 INFO  [main] org.tinymediamanager.TinyMediaManager:179 - System language  : cs_CZ
2015-10-14 00:54:09,504 INFO  [main] org.tinymediamanager.TinyMediaManager:180 - GUI language     : cs_CZ
2015-10-14 00:54:09,505 INFO  [main] org.tinymediamanager.TinyMediaManager:181 - Scraper language : ─îesk├Ż
2015-10-14 00:54:09,506 INFO  [main] org.tinymediamanager.TinyMediaManager:182 - TV Scraper lang  : ─îesk├Ż
2015-10-14 00:54:09,510 DEBUG [headless] org.tinymediamanager.TinyMediaManager:195 - starting without GUI...
2015-10-14 00:54:09,520 ERROR [headless] org.tinymediamanager.UpgradeTasks:155 - Could not update CMD TMM!
2015-10-14 00:54:09,523 DEBUG [headless] org.tinymediamanager.TinyMediaManager:227 - no splash found
2015-10-14 00:54:09,523 INFO  [headless] org.tinymediamanager.TinyMediaManager:230 - =====================================================
2015-10-14 00:54:09,524 INFO  [headless] org.tinymediamanager.TinyMediaManager:235 - starting tinyMediaManager
2015-10-14 00:54:09,630 ERROR [headless] org.tinymediamanager.core.Settings:766 - could not parse proxy port: null
2015-10-14 00:54:09,631 DEBUG [headless] org.tinymediamanager.TinyMediaManager:444 - Loading native mediainfo lib from: native/windows-x64
2015-10-14 00:54:10,436 INFO  [headless] org.tinymediamanager.TinyMediaManager:449 - Using MediaInfoLib - v0.7.78
2015-10-14 00:54:10,439 ERROR [headless] org.tinymediamanager.core.Utils:827 - Could not backup file backup\movies.db.2015-10-13.zip
2015-10-14 00:54:10,456 ERROR [headless] org.tinymediamanager.TinyMediaManager:349 - IllegalStateException
java.lang.IllegalStateException: The file is locked: nio:data\movies.db [1.4.188/7]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773) ~[h2-mvstore.jar:1.4.188]
        at org.h2.mvstore.FileStore.open(FileStore.java:172) ~[h2-mvstore.jar:1.4.188]
        at org.h2.mvstore.MVStore.<init>(MVStore.java:346) ~[h2-mvstore.jar:1.4.188]
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888) ~[h2-mvstore.jar:1.4.188]
        at org.tinymediamanager.core.movie.MovieModuleManager.startUp(MovieModuleManager.java:82) ~[tmm.jar:2.7-SNAPSHOT]
        at org.tinymediamanager.core.TmmModuleManager.enableModule(TmmModuleManager.java:55) ~[tmm.jar:2.7-SNAPSHOT]
        at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:269) ~[tmm.jar:2.7-SNAPSHOT]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) [na:1.8.0_60]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_60]
        at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_60]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_60]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_60]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_60]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_60]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_60]
2015-10-14 00:54:10,458 ERROR [headless] org.tinymediamanager.Log4jBackstop:37 - Uncaught exception in thread: headless
java.lang.IllegalStateException: The file is locked: nio:data\movies.db [1.4.188/7]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773) ~[h2-mvstore.jar:1.4.188]
        at org.h2.mvstore.FileStore.open(FileStore.java:172) ~[h2-mvstore.jar:1.4.188]
        at org.h2.mvstore.MVStore.<init>(MVStore.java:346) ~[h2-mvstore.jar:1.4.188]
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888) ~[h2-mvstore.jar:1.4.188]
        at org.tinymediamanager.core.movie.MovieModuleManager.startUp(MovieModuleManager.java:82) ~[tmm.jar:2.7-SNAPSHOT]
        at org.tinymediamanager.core.TmmModuleManager.enableModule(TmmModuleManager.java:55) ~[tmm.jar:2.7-SNAPSHOT]
        at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:269) ~[tmm.jar:2.7-SNAPSHOT]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[na:1.8.0_60]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_60]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_60]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_60]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_60]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_60]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_60]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_60]
```
