### ISSUE TITLE
Unable to Scrape TheTVDB.com

### ISSUE THREAD

**Issue by SPDurkee** [tinyMediaManager/tinyMediaManager#302]
__What TMM version are you using?__
2.9.12, fresh install

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
All searches to TheTVDB.com fail. Here is the error log:
02:34:19.889 ERROR org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider - TheTvDbMetadataProvider
java.lang.NullPointerException: null
	at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.initAPI(TheTvDbMetadataProvider.java:135)
	at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.search(TheTvDbMetadataProvider.java:170)
	at org.tinymediamanager.core.tvshow.TvShowList.searchTvShow(TvShowList.java:524)
	at org.tinymediamanager.ui.tvshows.dialogs.TvShowChooserDialog$SearchTask.doInBackground(TvShowChooserDialog.java:529)
	at org.tinymediamanager.ui.tvshows.dialogs.TvShowChooserDialog$SearchTask.doInBackground(TvShowChooserDialog.java:515)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
02:34:19.890 ERROR org.tinymediamanager.core.tvshow.TvShowList - searchTvShow
java.lang.NullPointerException: null
	at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.initAPI(TheTvDbMetadataProvider.java:135)
	at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.search(TheTvDbMetadataProvider.java:170)
	at org.tinymediamanager.core.tvshow.TvShowList.searchTvShow(TvShowList.java:524)
	at org.tinymediamanager.ui.tvshows.dialogs.TvShowChooserDialog$SearchTask.doInBackground(TvShowChooserDialog.java:529)
	at org.tinymediamanager.ui.tvshows.dialogs.TvShowChooserDialog$SearchTask.doInBackground(TvShowChooserDialog.java:515)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
02:34:23.771 ERROR org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider - problem getting data vom tvdb: null
02:34:32.010 ERROR org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider - problem getting data vom tvdb: null
02:34:33.081 ERROR org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider - problem getting data vom tvdb: null

__What is the expected behaviour?__
Searches to TheTVDB.com should work.

__Steps to reproduce:__
Any searched to TheTVDB.com will fail

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
tvdb has serious stability problems with their api (see https://forum.kodi.tv/showthread.php?tid=332352 and #301)

just retry to scrape...
