### ISSUE TITLE
getEpisodeCount error while scanning for new series

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#324]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_bf170ff_win

__release, pre-release, nightly, or directly from GitHub/branch?__
NIGHTLY

__What is the actual behaviour?__
I use a fresh tmm3 installation and scan for series over network shares and i got these error everytime.
![error](https://user-images.githubusercontent.com/3122325/41813518-ce6b7fc6-7737-11e8-86b4-8ce59128c587.png) 

__What is the expected behaviour?__
no error dialog

__Steps to reproduce:__
do setup dialog and add a series folder via smb and click finish

__Additional__
Have you attached the Logfile from the day it happened?
`org.jdesktop.beansbinding.PropertyResolutionException: Exception invoking method public int org.tinymediamanager.core.tvshow.TvShowList.getEpisodeCount() on org.tinymediamanager.core.tvshow.TvShowList@29741173
	at org.jdesktop.beansbinding.BeanProperty.invokeMethod(BeanProperty.java:626)
	at org.jdesktop.beansbinding.BeanProperty.read(BeanProperty.java:660)
	at org.jdesktop.beansbinding.BeanProperty.getProperty(BeanProperty.java:677)
	at org.jdesktop.beansbinding.BeanProperty.access$1900(BeanProperty.java:173)
	at org.jdesktop.beansbinding.BeanProperty$SourceEntry.updateCachedValue(BeanProperty.java:1048)
	at org.jdesktop.beansbinding.BeanProperty$SourceEntry.cachedValueChanged(BeanProperty.java:1076)
	at org.jdesktop.beansbinding.BeanProperty$SourceEntry.propertyValueChanged(BeanProperty.java:1123)
	at org.jdesktop.beansbinding.BeanProperty$SourceEntry.propertyChange(BeanProperty.java:1128)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at org.tinymediamanager.core.AbstractModelObject.firePropertyChange(AbstractModelObject.java:96)
	at org.tinymediamanager.core.tvshow.TvShowList.lambda$new$0(TvShowList.java:116)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport$1.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at org.tinymediamanager.ui.dialogs.TmmDialog.setVisible(TmmDialog.java:240)
	at org.tinymediamanager.ui.dialogs.MessageDialog.showExceptionWindow(MessageDialog.java:124)
	at org.tinymediamanager.Log4jBackstop.uncaughtException(Log4jBackstop.java:43)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.processException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at org.tinymediamanager.ui.dialogs.TmmDialog.setVisible(TmmDialog.java:240)
	at org.tinymediamanager.ui.dialogs.MessageDialog.showExceptionWindow(MessageDialog.java:124)
	at org.tinymediamanager.Log4jBackstop.uncaughtException(Log4jBackstop.java:43)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.processException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at org.tinymediamanager.ui.dialogs.TmmDialog.setVisible(TmmDialog.java:240)
	at org.tinymediamanager.ui.dialogs.MessageDialog.showExceptionWindow(MessageDialog.java:124)
	at org.tinymediamanager.Log4jBackstop.uncaughtException(Log4jBackstop.java:43)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.base/java.lang.ThreadGroup.uncaughtException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.processException(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jdesktop.beansbinding.BeanProperty.invokeMethod(BeanProperty.java:617)
	... 88 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.AbstractList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at org.tinymediamanager.core.tvshow.TvShowList.getEpisodeCount(TvShowList.java:257)
	... 92 more
`

Your Operating system? (win/mac/linux? version?)
Windows 10 x64

**Comment by mlaggner** [comment]
this issue is solved with the next build (in a few minutes)
