### ISSUE TITLE
NPE with Java 1.8.0_91

### ISSUE THREAD

**Issue by Vallimar** [tinyMediaManager/tinyMediaManager#33]
Version: 2.8-SNAPSHOT - NIGHTLY
Build: 2016-05-10 23:10
OS: Linux 4.5.3-300.xps.x86_64
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__

Receive an NPE warning when launching.
Application seems to function normally afterwards from what I can tell.

__What is the expected behaviour?__

To not receive an NPE error.

__Steps to reproduce:__

This error appears in stable and nightly branches and started occuring after I updated Java.

__Additional__
ERROR org.tinymediamanager.Log4jBackstop - Uncaught exception in thread: trackEventThread
java.lang.NullPointerException: null
	at java.net.URLEncoder.encode(URLEncoder.java:204) ~[na:1.8.0_91]
	at org.tinymediamanager.core.Utils.getEncProp(Utils.java:573) ~[tmm.jar:2.8-SNAPSHOT]
	at org.tinymediamanager.core.Utils.access$000(Utils.java:79) ~[tmm.jar:2.8-SNAPSHOT]
	at org.tinymediamanager.core.Utils$2.run(Utils.java:517) ~[tmm.jar:2.8-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]

**Comment by mlaggner** [comment]
should work in the latest nightly.
please confirm

**Comment by Vallimar** [comment]
No longer receiving the error when launching, thanks!
