### ISSUE TITLE
"Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper" in command line

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#371]
__What TMM version are you using?__
2.9.13

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
Can't run the commandline script specifying an alternate config.xml that came from a GUI machine.

__What is the expected behaviour?__
Run the commandline script with no errors.

__Steps to reproduce:__
- Enter the `data` folder in tinymediamanager installation. 
- Do `cp config.xml config2.xml`.
- Run the commandline script with the `-config config2.xml` parameter.

__Additional__
Have you attached the Logfile from the day it happened?

```
  1 Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper                          
  2         at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)         
  3         at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
  4         at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)                    
  5         at java.awt.EventQueue.isDispatchThread(EventQueue.java:1071)           
  6         at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1366)
  7         at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:91)
  8         at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
  9         at org.tinymediamanager.core.AbstractModelObject.firePropertyChange(AbstractModelObject.java:96)
 10         at org.tinymediamanager.core.Settings.setLanguage(Settings.java:1057)   
 11         at org.tinymediamanager.core.Settings$JaxbAccessorM_getLanguage_setLanguage_java_lang_String.set(MethodAccessor_Ref.java:45)
 12         at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:2    30)
 13         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.LeafPropertyLoader.text(LeafPropertyLoader.java:50)
 14         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.text(UnmarshallingContext.java:572)
 15         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.processText(SAXConnector.java:198)
 16         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:161)
 17         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
 18         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
 19         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImp    l.java:2967)
 20         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
 21         at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
 22         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
 23         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
 24         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
 25         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
 26         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
 27         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
 28         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
 29         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
 30         at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
 31         at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
 32         at org.tinymediamanager.core.Settings.getInstance(Settings.java:260)    
 33         at org.tinymediamanager.TinyMediaManagerCMD.parseParams(TinyMediaManagerCMD.java:143)
 34         at org.tinymediamanager.TinyMediaManager.main(TinyMediaManager.java:100)
```

Your Operating system? (win/mac/linux? version?)

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK Client VM (build 25.181-b13, mixed mode)

openjdk-8-jdk-headless/stable,now 8u181-b13-1~deb9u1 armhf [installed]
  OpenJDK Development Kit (JDK) (headless)

openjdk-8-jre-headless/stable,now 8u181-b13-1~deb9u1 armhf [installed]
  OpenJDK Java runtime, using Hotspot JIT (headless)

Debian 9.4

Following https://askubuntu.com/a/1000944:

> For those who do not have root access on their machines to change the configuration file or do not want to install the full JRE: append -Djavax.accessibility.assistive_technologies=" " to your command

Adding this line to https://github.com/tinyMediaManager/tinyMediaManager/blob/master/AppBundler/dist-linux/tinyMediaManagerCMD.sh#L10 it works. But I don't know if this is the correct approach.

**Comment by mlaggner** [comment]
good find - will add this to the shell script
