### ISSUE TITLE
ofdb keeps throwing error on console

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#372]
__What TMM version are you using?__
2.9.13

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
ofdb keeps throwing error on console

__What is the expected behaviour?__
Find or not find something in the parsing. instead of throwing an error.

__Steps to reproduce:__
- Run the commandline script `tinyMediaManagerCMD.sh -updateMovies -scrapeNew -rename` in a simple movie. `<scraperFallback>true</scraperFallback>` is set in my `config.xml`.

__Additional__
Have you attached the Logfile from the day it happened?

```
2018-08-21 22:43:14,327 ERROR [tmmpool-scrape-T3] org.tinymediamanager.scraper.http.Url:312 - Exception getting url http://www.ofdb.de/view.php?page=suchergebnis&Kat=IMDb&SText=ttXXXXXX ; none
java.nio.charset.UnsupportedCharsetException: none
	at java.nio.charset.Charset.forName(Charset.java:531)
	at okhttp3.MediaType.charset(MediaType.java:95)
	at org.tinymediamanager.scraper.http.Url.getInputStream(Url.java:298)
	at org.tinymediamanager.scraper.ofdb.OfdbMetadataProvider.getTrailers(OfdbMetadataProvider.java:667)
	at org.tinymediamanager.core.movie.tasks.MovieScrapeTask$Worker.getTrailers(MovieScrapeTask.java:309)
	at org.tinymediamanager.core.movie.tasks.MovieScrapeTask$Worker.run(MovieScrapeTask.java:203)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-21 22:43:14,329 ERROR [tmmpool-scrape-T3] o.t.scraper.ofdb.OfdbMetadataProvider:808 - Error parsing http://www.ofdb.de/view.php?page=suchergebnis&Kat=IMDb&SText=ttXXXXXX
2018-08-21 22:43:14,331 ERROR [tmmpool-scrape-T3] o.t.core.movie.tasks.MovieScrapeTask:316 - getTrailers
java.lang.NullPointerException: null
	at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:163)
	at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:179)
	at org.jsoup.helper.DataUtil.load(DataUtil.java:59)
	at org.jsoup.Jsoup.parse(Jsoup.java:118)
	at org.tinymediamanager.scraper.ofdb.OfdbMetadataProvider.getTrailers(OfdbMetadataProvider.java:668)
	at org.tinymediamanager.core.movie.tasks.MovieScrapeTask$Worker.getTrailers(MovieScrapeTask.java:309)
	at org.tinymediamanager.core.movie.tasks.MovieScrapeTask$Worker.run(MovieScrapeTask.java:203)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Your Operating system? (win/mac/linux? version?)

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK Client VM (build 25.181-b13, mixed mode)

openjdk-8-jdk-headless/stable,now 8u181-b13-1~deb9u1 armhf [installed]
  OpenJDK Development Kit (JDK) (headless)

openjdk-8-jre-headless/stable,now 8u181-b13-1~deb9u1 armhf [installed]
  OpenJDK Java runtime, using Hotspot JIT (headless)

Debian 9.4

**Comment by mlaggner** [comment]
I've never seen this issue and ofdb is working here..
at the beginning of the log (at startup) there are some lines according the charset - could you find them and paste them?
do you have UTF8 support in your locale?

**Comment by msdos** [comment]
```
2018-08-28 00:35:21,307 INFO  [main] org.tinymediamanager.TinyMediaManager:160 - =====================================================
2018-08-28 00:35:21,311 INFO  [main] org.tinymediamanager.TinyMediaManager:161 - === tinyMediaManager (c) 2012-2018 Manuel Laggner ===
2018-08-28 00:35:21,312 INFO  [main] org.tinymediamanager.TinyMediaManager:162 - =====================================================
2018-08-28 00:35:21,322 INFO  [main] org.tinymediamanager.TinyMediaManager:163 - tmm.version      : 2.9.13
2018-08-28 00:35:21,323 INFO  [main] org.tinymediamanager.TinyMediaManager:169 - os.name          : Linux
2018-08-28 00:35:21,324 INFO  [main] org.tinymediamanager.TinyMediaManager:170 - os.version       : 4.14.62-v7+
2018-08-28 00:35:21,325 INFO  [main] org.tinymediamanager.TinyMediaManager:171 - os.arch          : arm
2018-08-28 00:35:21,347 INFO  [main] org.tinymediamanager.TinyMediaManager:173 - java.version     : 1.8.0_181
2018-08-28 00:35:21,349 INFO  [main] org.tinymediamanager.TinyMediaManager:602 - default encoding : UTF-8 | UTF8 | UTF-8
2018-08-28 00:35:21,351 INFO  [main] org.tinymediamanager.TinyMediaManager:602 - set encoding to  : UTF-8 | UTF8 | UTF-8
2018-08-28 00:35:21,352 INFO  [main] org.tinymediamanager.TinyMediaManager:202 - System language  : en_GB
2018-08-28 00:35:21,353 INFO  [main] org.tinymediamanager.TinyMediaManager:203 - GUI language     : en_US
2018-08-28 00:35:21,396 INFO  [main] org.tinymediamanager.TinyMediaManager:204 - Scraper language : English
2018-08-28 00:35:21,403 INFO  [main] org.tinymediamanager.TinyMediaManager:205 - TV Scraper lang  : English
2018-08-28 00:35:21,524 INFO  [headless] org.tinymediamanager.TinyMediaManager:233 - =====================================================
2018-08-28 00:35:21,526 INFO  [headless] org.tinymediamanager.TinyMediaManager:258 - starting tinyMediaManager
2018-08-28 00:35:22,234 INFO  [headless] o.t.thirdparty.MediaInfoUtils:74 - Using MediaInfoLib - v0.7.91
```
```
# locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```

**Comment by msdos** [comment]
Doing a `curl -L -I https://ssl.ofdb.de/view.php?page=suchergebnis&Kat=IMDb&SText=tt6499752`:

 ```
HTTP/1.1 301 Moved Permanently
Date: Tue, 28 Aug 2018 03:53:59 GMT
Server: Apache
Location: https://ssl.ofdb.de/view.php?page=suchergebnis&Kat=IMDb&SText=tt6499752
Connection: close
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Tue, 28 Aug 2018 03:54:02 GMT
Server: Apache
Set-Cookie: ofdb_theme=0; expires=Wed, 28-Aug-2019 03:54:02 GMT; path=/; domain=.ofdb.de
Set-Cookie: ofdb_ret=view.php%253Fpage%253Dstart; path=/; domain=.ofdb.de
Connection: close
Content-Type: text/html; charset=none

```

It seems that the server is incorrectly sending a `none` encoding and breaking the scraper:

```
ERROR [tmmpool-scrape-T3] org.tinymediamanager.scraper.http.Url:312 - Exception getting url http://www.ofdb.de/view.php?page=suchergebnis&Kat=IMDb&SText=ttXXXXXX ; none
java.nio.charset.UnsupportedCharsetException: none
```

Should we have a fallback encode to avoid this problem, and after implementing the fallback encoding close this issue since it's webserver related (like https://github.com/tinyMediaManager/tinyMediaManager/issues/373)? IMHO, the fallback encoding should be what you already list at the top of the logs.

**Comment by ProIcons** [comment]
That's odd cause we define in jsoup the charset 

```
Jsoup.parse(in, "UTF-8", "");
```

**Comment by mlaggner** [comment]
We may add a network interceptor ( https://github.com/square/okhttp/wiki/Interceptors) to _ clean_ the response..
On the other hand ofdb is a scraper with a non official api and personally I don't want to fix their problems because of using a HTML scraper...

**Comment by msdos** [comment]
> On the other hand ofdb is a scraper with a non official api and personally I don't want to fix their problems because of using a HTML scraper

I understand. Should we just swallow the error in the application then? Or just do nothing?

**Comment by mlaggner** [comment]
just tried that example at home, and I did not get any exception (at least with tmm v3)
with tmm v2 there is such an exception.

would it be enough if that is fixed in v3? since fixing that would need to update some dependencies/api and I would not like to touch this in v2, because all our energy flows into v3 now..

**Comment by msdos** [comment]
Yes, it will be enough. You already said all efforts would be for tmmv3. It's fine by me since you're the maintainers of this project.

If this is already fixed in tmmv3, this issue can be closed. Is someone searches for the same traceback they will see that it works in tmmv3.
