### ISSUE TITLE
Error Scraping THETVDB

### ISSUE THREAD

**Issue by akovia** [tinyMediaManager/tinyMediaManager#393]
__What TMM version are you using?__
3.0-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__
Build date: 2018-09-20 00:35

__What is the actual behaviour?__
Throws error when scraping TV Show

__What is the expected behaviour?__

__Steps to reproduce:__

- Select thetvdb as scraper
- When correct show is selected, press OK

__Additional__
Have you attached the Logfile from the day it happened?
```
java.lang.NullPointerException
	at org.tinymediamanager.core.tvshow.tasks.TvShowActorImageFetcherTask.<init>(TvShowActorImageFetcherTask.java:45)
	at org.tinymediamanager.core.tvshow.entities.TvShowEpisode.writeActorImages(TvShowEpisode.java:1518)
	at org.tinymediamanager.core.tvshow.entities.TvShowEpisode.setMetadata(TvShowEpisode.java:674)
	at org.tinymediamanager.core.tvshow.tasks.TvShowEpisodeScrapeTask.doInBackground(TvShowEpisodeScrapeTask.java:141)
	at org.tinymediamanager.core.threading.TmmTask.run(TmmTask.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Your Operating system? (win/mac/linux? version?)
Arch Linux: 4.18.7-arch1-1-ARCH

**Comment by mlaggner** [comment]
should be fixed in the next build
