### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by EGrunzke** [tinyMediaManager/tinyMediaManager#4]
I ran into a ConcurrentModificationException while scrapingsome movies.  Interstingly, the operation still finished as far as I can tell.  Here's my repro steps:

1. Sort by rating (this brings the 0s to the top)
2. Select 6 unscraped movies
3. Select "Search and scrape selected movie(s) - Force best match" from the dropdown
4. Get popup with this stack trace.
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.objectdb.o.ITW.next(ITW.java:73)
	at ca.odell.glazedlists.AbstractEventList.addAll(AbstractEventList.java:336)
	at ca.odell.glazedlists.TransformedList.addAll(TransformedList.java:84)
	at ca.odell.glazedlists.AbstractEventList.addAll(AbstractEventList.java:295)
	at ca.odell.glazedlists.impl.ThreadSafeList.addAll(ThreadSafeList.java:213)
	at org.tinymediamanager.ui.movies.MovieTrailerPanel$1.propertyChange(MovieTrailerPanel.java:118)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at org.tinymediamanager.core.AbstractModelObject.firePropertyChange(AbstractModelObject.java:109)
	at org.tinymediamanager.ui.movies.MovieSelectionModel.access$100(MovieSelectionModel.java:40)
	at org.tinymediamanager.ui.movies.MovieSelectionModel$1.propertyChange(MovieSelectionModel.java:90)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at javax.swing.event.SwingPropertyChangeSupport$1.run(SwingPropertyChangeSupport.java:97)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It's only happened the once, and I know that multithreaded exceptions are often intermittent, but I wanted to submit the trace anyway.  I'll follow up if it happens again.

**Comment by mlaggner** [comment]
thanks for the hint.
in fact it is a (really rare) multithreading exception caused by the underlying database engine. Since we changed the engine for 2.7 we may not see this issue again, but nevertheless I will check the code for some enhancements
