### ISSUE TITLE
crash on launch - Java heap space

### ISSUE THREAD

**Issue by tatsumasagc** [tinyMediaManager/tinyMediaManager#450]
__What TMM version are you using?__
2.9.15 69b6104

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
crash on launch

__What is the expected behaviour?__
open app

__Steps to reproduce:__
- first - double click tinyMediaManager.exe

__Additional__
Have you attached the Logfile from the day it happened?
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryOutputStream.write(ZipFileSystem.java:1596)
	at java.base/java.io.InputStream.transferTo(InputStream.java:705)
	at java.base/java.nio.file.Files.copy(Files.java:3077)
	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:126)
	at java.base/java.nio.file.Files.copy(Files.java:1297)
	at org.tinymediamanager.core.Utils.createZip(Utils.java:1273)
	at org.tinymediamanager.core.Utils.createBackupFile(Utils.java:1046)
	at org.tinymediamanager.core.Utils.createBackupFile(Utils.java:1007)
	at org.tinymediamanager.core.tvshow.TvShowModuleManager.startUp(TvShowModuleManager.java:87)
	at org.tinymediamanager.core.TmmModuleManager.enableModule(TmmModuleManager.java:55)
	at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:297)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Your Operating system? (win/mac/linux? version?)
Windows 10

**Comment by myron0815** [comment]
per default, TMM should run with bare 64mb RAM... 
How much do you have? and how much free?

Can you upload the launcher.log and TMM.log to some pastebin site?
Creating a ZIP file with your old logs should not reserve much RAM...
As workaround, try deleting the /logs/ folder.....
