### ISSUE TITLE
Error with scraping fanart

### ISSUE THREAD

**Issue by timothymowens** [tinyMediaManager/tinyMediaManager#46]
__What TMM version are you using?__
2.8.1

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
Error is reported in both the GUI and the commandline script.  Note: I tried scraping from all available sources, error still occurred.

Here is the error:

```
2016-06-18 12:28:29,339 ERROR [tmmpool-scrape-thread-1] o.t.core.tvshow.tasks.TvShowScrapeTask:236 - getArtwork
retrofit.RetrofitError: 404 Not Found
	at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit.jar:na]
	at com.sun.proxy.$Proxy38.getTvShowImages(Unknown Source) ~[na:na]
	at org.tinymediamanager.scraper.fanarttv.FanartTvMetadataProvider.getTvShowArtwork(FanartTvMetadataProvider.java:173) ~[na:na]
	at org.tinymediamanager.scraper.fanarttv.FanartTvMetadataProvider.getArtwork(FanartTvMetadataProvider.java:99) ~[na:na]
	at org.tinymediamanager.core.tvshow.tasks.TvShowScrapeTask$Worker.getArtwork(TvShowScrapeTask.java:233) [tmm.jar:2.8.1]
	at org.tinymediamanager.core.tvshow.tasks.TvShowScrapeTask$Worker.run(TvShowScrapeTask.java:192) [tmm.jar:2.8.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

__What is the expected behaviour?__
No error.

__Steps to reproduce:__
In the GUI, I simply selected "Search and scrape selected TV Show(s)".  In the commandline script, I ran: `/opt/tiny_media_manager/tinyMediaManagerCMD.sh -updateTv -scrapeNew -renameNew`

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Operating system is Ubuntu 16.04 64-bit.  
Java version is:
```
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by myron0815** [comment]
It works for me (atm)
Mybe it was just a temporary error?
Error 404 means, that we couldn't access a webpage...

Can you post more logs?

**Comment by timothymowens** [comment]
My apologies, I forgot to remove my bug.  You can close it.  It was
temporary.

**Comment by myron0815** [comment]
great, thx :)
