### ISSUE TITLE
can't scrape with thetvdb anymore, since latest update to 2.9.17

### ISSUE THREAD

**Issue by fsyy** [tinyMediaManager/tinyMediaManager#478]
__What TMM version are you using?__
2.9.17

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
does nothing when using thetvdb scraper, no errors. trakt.tv does work

__What is the expected behaviour?__
scrape from thetvdb

__Steps to reproduce:__
- first update to 2.9.17
- second try to scrape a tv episode

__Additional__
Have you attached the Logfile from the day it happened? 

while starting up tmm:

2019-05-15 08:06:01,138 WARN  [main] o.t.scraper.config.MediaProviderConfig:83 - Cannot load settings 'data/scraper_moviemeter.conf' - using defaults
2019-05-15 08:06:01,147 WARN  [main] o.t.scraper.config.MediaProviderConfig:83 - Cannot load settings 'data/scraper_tmdb.conf' - using defaults

while trying to scrape a episode:

```
2019-05-15 08:06:32,571 ERROR [tmmpool-unnamed-task-T2-G3] o.t.s.thetvdb.TheTvDbMetadataProvider:140 - TheTvDbMetadataProvider
java.net.ConnectException: Failed to connect to api.thetvdb.com/0.0.0.0:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.initAPI(TheTvDbMetadataProvider.java:136)
        at org.tinymediamanager.scraper.thetvdb.TheTvDbMetadataProvider.getMetadata(TheTvDbMetadataProvider.java:154)
        at org.tinymediamanager.core.tvshow.tasks.TvShowEpisodeScrapeTask.doInBackground(TvShowEpisodeScrapeTask.java:133)
        at org.tinymediamanager.core.threading.TmmTask.run(TmmTask.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
        ... 25 common frames omitted
2019-05-15 08:06:32,572 WARN  [tmmpool-unnamed-task-T2-G3] o.t.c.t.tasks.TvShowEpisodeScrapeTask:139 - Error getting metadata Failed to connect to api.thetvdb.com/0.0.0.0:443
```

Your Operating system? (win/mac/linux? version?)
Arch Linux - Kernel: 5.0.13

**Comment by myron0815** [comment]
works for me.  
Just scraped a show with TVDB

>Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)  
Your could not connect to TMDB; in fact, the connection was refused!  
Maybe some hiccup on their side?

**Comment by fsyy** [comment]
funny coincidence, i updated, scraping didn't work anymore, i also tried to connect to api.thetvdb.org and it worked.
i didn't try to connect to https://api.thetvdb.org, i would have recognized that this wouldn't work.
i restarted my router and that did the trick.
so this issue can be closed, thanks for all your work!
