### ISSUE TITLE
Error updating directories

### ISSUE THREAD

**Issue by redflo** [tinyMediaManager/tinyMediaManager#49]
Version: 2.8.1
Build: 2016-06-15 19:06
OS: Linux 4.1.26-21-default
JDK: 1.8.0_74 amd64 Oracle Corporation

__What is the actual behaviour?__

Klick update, then a Exception shows:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at ca.odell.glazedlists.AbstractEventList.addAll(AbstractEventList.java:336)
	at ca.odell.glazedlists.TransformedList.addAll(TransformedList.java:84)
	at ca.odell.glazedlists.AbstractEventList.addAll(AbstractEventList.java:295)
	at org.tinymediamanager.ui.moviesets.MovieSetInformationPanel$1.propertyChange(MovieSetInformationPanel.java:220)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at org.tinymediamanager.core.AbstractModelObject.firePropertyChange(AbstractModelObject.java:109)
	at org.tinymediamanager.ui.moviesets.MovieSetSelectionModel.access$000(MovieSetSelectionModel.java:36)
	at org.tinymediamanager.ui.moviesets.MovieSetSelectionModel$1.propertyChange(MovieSetSelectionModel.java:54)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at javax.swing.event.SwingPropertyChangeSupport$1.run(SwingPropertyChangeSupport.java:97)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Movies are not 

__What is the expected behaviour?__

No Exception

__Steps to reproduce:__

Click update

__Additional__
Have you attached the logfile from the day it happened?

Not yet, Logfiles contain too much personal data. Ask me for specific logs and i will upload cleaned logs.

**Comment by mlaggner** [comment]
this is a random hiccup - please try again.
I'll increase stability of multithreading soon
