### ISSUE TITLE
tinyMediaManagerCMD.exe scrapeNew doesnt work

### ISSUE THREAD

**Issue by pschonmann** [tinyMediaManager/tinyMediaManager#5]
```
d:\Appz\tinymediamanager>tinyMediaManagerCMD.exe -scrapeNew
2015-10-20 12:29:17,739 DEBUG [main] org.tinymediamanager.TinyMediaManager:91 - TMM started with: [-scrapeNew]
2015-10-20 12:29:17,757 INFO  [main] org.tinymediamanager.TinyMediaManager:141 - =====================================================
2015-10-20 12:29:17,758 INFO  [main] org.tinymediamanager.TinyMediaManager:142 - === tinyMediaManager (c) 2012-2015 Manuel Laggner ===
2015-10-20 12:29:17,758 INFO  [main] org.tinymediamanager.TinyMediaManager:143 - =====================================================
2015-10-20 12:29:17,763 INFO  [main] org.tinymediamanager.TinyMediaManager:144 - tmm.version      : 2.7-SNAPSHOT - NIGHTLY
2015-10-20 12:29:18,231 INFO  [main] org.tinymediamanager.TinyMediaManager:147 - tmm.supporter    : THANKS FOR DONATING - ALL FEATURES UNLOCKED :)
2015-10-20 12:29:18,231 INFO  [main] org.tinymediamanager.TinyMediaManager:150 - os.name          : Windows 10
2015-10-20 12:29:18,232 INFO  [main] org.tinymediamanager.TinyMediaManager:151 - os.version       : 10.0
2015-10-20 12:29:18,234 INFO  [main] org.tinymediamanager.TinyMediaManager:152 - os.arch          : amd64
2015-10-20 12:29:18,240 INFO  [main] org.tinymediamanager.TinyMediaManager:154 - java.version     : 1.8.0_60
2015-10-20 12:29:18,241 INFO  [main] org.tinymediamanager.TinyMediaManager:589 - default encoding : UTF-8 | UTF8 | UTF-8
2015-10-20 12:29:18,245 INFO  [main] org.tinymediamanager.TinyMediaManager:589 - set encoding to  : UTF-8 | UTF8 | UTF-8
2015-10-20 12:29:18,249 INFO  [main] org.tinymediamanager.TinyMediaManager:179 - System language  : cs_CZ
2015-10-20 12:29:18,251 INFO  [main] org.tinymediamanager.TinyMediaManager:180 - GUI language     : cs_CZ
2015-10-20 12:29:18,254 INFO  [main] org.tinymediamanager.TinyMediaManager:181 - Scraper language : ─îesk├Ż
2015-10-20 12:29:18,256 INFO  [main] org.tinymediamanager.TinyMediaManager:182 - TV Scraper lang  : ─îesk├Ż
2015-10-20 12:29:18,266 DEBUG [headless] org.tinymediamanager.TinyMediaManager:195 - starting without GUI...
2015-10-20 12:29:18,278 ERROR [headless] org.tinymediamanager.UpgradeTasks:198 - Could not update CMD TMM!
2015-10-20 12:29:18,282 DEBUG [headless] org.tinymediamanager.TinyMediaManager:227 - no splash found
2015-10-20 12:29:18,282 INFO  [headless] org.tinymediamanager.TinyMediaManager:230 - =====================================================
2015-10-20 12:29:18,283 INFO  [headless] org.tinymediamanager.TinyMediaManager:235 - starting tinyMediaManager
2015-10-20 12:29:18,397 ERROR [headless] org.tinymediamanager.core.Settings:766 - could not parse proxy port: null
2015-10-20 12:29:18,398 DEBUG [headless] org.tinymediamanager.TinyMediaManager:444 - Loading native mediainfo lib from: native/windows-x64
2015-10-20 12:29:18,561 INFO  [headless] org.tinymediamanager.TinyMediaManager:449 - Using MediaInfoLib - v0.7.78
2015-10-20 12:29:19,230 INFO  [headless] o.tinymediamanager.core.movie.MovieList:313 - found 243 movies in database
2015-10-20 12:29:19,233 INFO  [headless] o.tinymediamanager.core.movie.MovieList:333 - found 61 movieSets in database
2015-10-20 12:29:19,513 INFO  [headless] o.t.core.tvshow.TvShowList:248 - found 13 TV shows in database
2015-10-20 12:29:19,745 INFO  [headless] o.t.core.tvshow.TvShowList:278 - found 1278 episodes in database
2015-10-20 12:29:19,782 DEBUG [headless] org.tinymediamanager.core.PluginManager:61 - loading classpath plugins...
2015-10-20 12:29:19,782 DEBUG [headless] org.tinymediamanager.core.PluginManager:69 - Done loading classpath plugins - took 0 -
2015-10-20 12:29:19,783 DEBUG [headless] org.tinymediamanager.core.PluginManager:73 - loading external plugins...
2015-10-20 12:29:19,859 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:240 - searching for Kodi commons
2015-10-20 12:29:19,954 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.common.musicbrainz.org - ID already imported, or version lower
2015-10-20 12:29:19,958 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.common.themoviedb.org - ID already imported, or version lower
2015-10-20 12:29:19,959 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.common.movieposterdb.com\movieposterdb.xml
2015-10-20 12:29:19,960 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.common.musicbrainz.org\musicbrainz.xml
2015-10-20 12:29:19,962 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.common.ofdb.de\ofdbcommon.xml
2015-10-20 12:29:19,965 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.common.port.hu\porthu.xml
2015-10-20 12:29:19,967 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.common.rt.com\rt.xml
2015-10-20 12:29:19,970 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.common.themoviedb.org\tmdb.xml
2015-10-20 12:29:19,973 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Program Files (x86)\Kodi\addons\metadata.common.allmusic.com\allmusic.xml
2015-10-20 12:29:19,975 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Program Files (x86)\Kodi\addons\metadata.common.fanart.tv\fanarttv.xml
2015-10-20 12:29:19,981 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Program Files (x86)\Kodi\addons\metadata.common.htbackdrops.com\htbackdrops.xml
2015-10-20 12:29:19,984 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Program Files (x86)\Kodi\addons\metadata.common.imdb.com\imdb.xml
2015-10-20 12:29:19,987 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Program Files (x86)\Kodi\addons\metadata.common.last.fm\lastfm.xml
2015-10-20 12:29:19,989 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: C:\Program Files (x86)\Kodi\addons\metadata.common.theaudiodb.com\tadb.xml
2015-10-20 12:29:19,992 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:170 - searching for Kodi scrapers
2015-10-20 12:29:20,034 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.album.universal - ID already imported, or version lower
2015-10-20 12:29:20,037 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.artists.universal - ID already imported, or version lower
2015-10-20 12:29:20,040 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.musicvideos.theaudiodb.com - ID already imported, or version lower
2015-10-20 12:29:20,044 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.themoviedb.org - ID already imported, or version lower
2015-10-20 12:29:20,047 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding C:\Program Files (x86)\Kodi\addons\metadata.tvdb.com - ID already imported, or version lower
2015-10-20 12:29:20,048 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.album.universal\albumuniversal.xml
2015-10-20 12:29:20,050 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.artists.universal\artistuniversal.xml
2015-10-20 12:29:20,053 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.musicvideos.theaudiodb.com\tadb.xml
2015-10-20 12:29:20,055 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.themoviedb.org\tmdb.xml
2015-10-20 12:29:20,058 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.themusicvideodb.org\tmvdb.xml
2015-10-20 12:29:20,064 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.tvdb.com\tvdb.xml
2015-10-20 12:29:20,067 DEBUG [headless] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: C:\Users\Petr\AppData\Roaming\Kodi\addons\metadata.universal\universal.xml
2015-10-20 12:29:20,259 DEBUG [headless] org.tinymediamanager.core.PluginManager:81 - Done loading external plugins - took 475 - 00:00:00
2015-10-20 12:29:20,262 INFO  [updateThread] org.tinymediamanager.core.UpdaterTask:67 - Checking for updates...
2015-10-20 12:29:20,265 ERROR [trackEventThread] org.tinymediamanager.Log4jBackstop:37 - Uncaught exception in thread: trackEventThread
java.awt.HeadlessException: null
        at sun.awt.HeadlessToolkit.getScreenSize(Unknown Source) ~[na:1.8.0_60]
        at org.tinymediamanager.core.Utils$2.run(Utils.java:363) ~[tmm.jar:2.7-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_60]
2015-10-20 12:29:20,277 DEBUG [updateThread] org.tinymediamanager.scraper.http.Url:232 - getting http://nightly.tinymediamanager.org/build/digest.txt?z=1445336960264
2015-10-20 12:29:20,438 INFO  [updateThread] org.tinymediamanager.core.UpdaterTask:150 - Already up2date :)
2015-10-20 12:29:20,442 INFO  [updateThread] org.tinymediamanager.TinyMediaManager:330 - bye bye
2015-10-20 12:29:20,511 ERROR [updateThread] org.tinymediamanager.core.Settings:766 - could not parse proxy port: null
```

**Comment by mlaggner** [comment]
the -scrapeNew parameter is a bit misleading (we are aware of that, but we did not find any other solution yet):
-scrapeNew does only scrape new items found in the _same_ run (so you probably need -updateMovies first)

**Comment by myron0815** [comment]
in fact, you need to set "-update -scrapeNew" as a single command.
"scrapeNew" only scrapes movies/shows which have been found in the same run :|
We have already an issue, to better define "new"...
Thanks for reporting
