### ISSUE TITLE
NullPointerException when scraping movie on OK click

### ISSUE THREAD

**Issue by Stefan-Code** [tinyMediaManager/tinyMediaManager#54]
tmm version `2.8.2-snapshot`

compiled directly from `47fde9d`

When scraping a movie a NullPointerException occurs. This only seems to affect movies with missing artwork.

Right-Click to search and scrape -> Select matching movie from list -> Click OK -> EXCEPTION

This does not happen when I `mvn compile` the tag `tinyMediaManager-2.8.1`.

I am running 

```
Linux sk2 4.4.0-21-generic #37~14.04.1-Ubuntu SMP Wed Apr 20 16:33:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

[The Logfile can be found here](http://pastebin.com/3tsXa2CK)

Exception excerpt:
```
java.lang.NullPointerException: null
    at org.tinymediamanager.core.movie.connector.MovieToXbmcNfoConnector.createInstanceFromMovie(MovieToXbmcNfoConnector.java:405) ~[tmm.jar:2.8.2-SNAPSHOT]
    at org.tinymediamanager.core.movie.connector.MovieToXbmcNfoConnector.setData(MovieToXbmcNfoConnector.java:197) ~[tmm.jar:2.8.2-SNAPSHOT]
    at org.tinymediamanager.core.movie.entities.Movie.writeNFO(Movie.java:1328) ~[tmm.jar:2.8.2-SNAPSHOT]
    at org.tinymediamanager.core.movie.entities.Movie.setMetadata(Movie.java:942) ~[tmm.jar:2.8.2-SNAPSHOT]
    at org.tinymediamanager.ui.movies.dialogs.MovieChooserDialog.actionPerformed(MovieChooserDialog.java:413) [tmm.jar:2.8.2-SNAPSHOT]
```

**Comment by mlaggner** [comment]
https://github.com/tinyMediaManager/tinyMediaManager/commit/73a18c6903dcc5097c372012eba507b98e806d13 should have fixed that
