### ISSUE TITLE
cannot scan new movies ...

### ISSUE THREAD

**Issue by peram1** [tinyMediaManager/tinyMediaManager#55]
Version: 2.8.2-SNAPSHOT - PRE-RELEASE
Build: 2016-07-08 09:49
OS: Linux 3.19.0-32-generic
JDK: 1.7.0_101 amd64 Oracle Corporation

__What is the actual behaviour?__
error message when scanning a new movie via
"suchen & scrapen aller ausgewählten Filme"

__What is the expected behaviour?__
scan it

__Steps to reproduce:__
have an unscanned movie and try to scan

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/355479/tmm_logs.zip)

**Comment by Stefan-Code** [comment]
That's the [same problem I had](https://github.com/tinyMediaManager/tinyMediaManager/issues/54) (or still have, trying to figure that out right now...)

**Comment by Stefan-Code** [comment]
To me it seems like https://github.com/tinyMediaManager/tinyMediaManager/commit/73a18c6903dcc5097c372012eba507b98e806d13 fixes this problem for some, but not all movies. But I can't really spot a difference between the working movies and the ones where it fails.

**Comment by mlaggner** [comment]
73a18c6 should have fixed that

**Comment by Stefan-Code** [comment]
https://github.com/tinyMediaManager/tinyMediaManager/commit/73a18c6903dcc5097c372012eba507b98e806d13 doesn't fix it for me. Some movies still throw the Error. Very rarely though.

Stacktrace is:
```
java.lang.NullPointerException
	at org.tinymediamanager.core.movie.connector.MovieToXbmcNfoConnector.createInstanceFromMovie(MovieToXbmcNfoConnector.java:405)
	at org.tinymediamanager.core.movie.connector.MovieToXbmcNfoConnector.setData(MovieToXbmcNfoConnector.java:197)
	at org.tinymediamanager.core.movie.entities.Movie.writeNFO(Movie.java:1328)
	at org.tinymediamanager.core.movie.entities.Movie.setMetadata(Movie.java:942)
	at org.tinymediamanager.ui.movies.dialogs.MovieChooserDialog.actionPerformed(MovieChooserDialog.java:413)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	[...]
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.tinymediamanager.ui.dialogs.TmmDialog.setVisible(TmmDialog.java:84)
	at org.tinymediamanager.ui.movies.dialogs.MovieChooserDialog.showDialog(MovieChooserDialog.java:614)
	at org.tinymediamanager.ui.movies.actions.MovieSingleScrapeAction.actionPerformed(MovieSingleScrapeAction.java:66)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	[...]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by mlaggner** [comment]
the line 405 from your stacktrace is an empty line in 367682d ...

**Comment by Stefan-Code** [comment]
That is really weird.
I have checked out the `devel` branch.
```
sk@sk ~/Programming/tinyMediaManager/build (devel) $ git rev-parse HEAD
367682d8af884c0ea363c62bbe9236028c926b8b
```
then `mvn compile` and `mvn package`. Then `./tinyMediaManager.sh` from the `build` directory.

Anything wrong with that approach?
